#+title: Praja Case Study

* Introduction
Praja is a non-partisan organization working towards enbaling accountable governance since 1997. Non partisan means free from party affiliations.

Praja believe that the governance structures in urban India lack true grassroots democracy. The lack of effective governance is caused by: unresponsible ER and lack of power

It works with leader ship to identify and address problems and improve work processes in urban governance

* Objective
- Simplifying people's lives
  - fairness, transparency, and accountability in decision-making.
  - reducing corruption and ensuring justice, helps build a stable and prosperous society
- Tools for better governance
  - White papers
    - A white paper is an authoritative document that provides detailed information and analysis on a specific topic, often presenting a problem and proposing solutions. They are commonly used in business and government to inform decision-making and persuade readers about a particular viewpoint or product.
  - ER report cards
    - ER Reports cards rank city councillors and MLAs on their annual performance to make elected representatives accountable for performance of their key duties and to make citizens involved beyond voting to monitor the performance of their representatives on a regular basis.
  - Urban governance reports
    - Urban Governance Reports map the implementation of the 74th Constitutional Amendment across all states in India by reviewing the existing governance and institutional structures in place across Indian cities with the aim of reforming and empowering urban governments.

* Initiative
- Praja collaboration with Brihanmumbai Municipal Corportation (BMC) to make the first 'Citizen Charter of Mumbai' - 1999
    - A Citizen's Charter is an official document that outlines the quality of service that citizens can expect from their government or public service providers.

- Developed a Citizen's Grievanve Redressal Mechanism with BMC - 2003
    - Has resolved 89,553 complaints in 2022
    - still active

- white paper on issuses related to civic, health, crime, education and housing in Mumbai and Delhi.

- Started publishing Annual Report Cards to track performances of Members of the Legislative Assembly (MLAs) and Councilor's in Mumbai since 2011 and in Delhi since 2016.

- Conducted an Urban Governance Reforms Study to map the implementation of 74th Amendment and status of urban reforms in all states to identify levers and barriers and to identify a set of recommendations - 2017

- Developed 'Urban Governancee Index 2020' to assess the present status of reform implementation, with the larger goal of forging a network of key influencers, thought leaders and local government bodies to democratise city governments.
